apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-rollout-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DevUnnati/argo-rollouts-argocd.git
    targetRevision: main
    path: overlay/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
   
