apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# base resources
resources:
  - ../../base

# patches for dev environment (use modern 'patches')
patches:
  - path: patch-rollout.yaml
    target:
      kind: Rollout
      name: demo-rollout
